from apps.stock_data_management.container import StockDataManagementContainer


stock_data_management_container = StockDataManagementContainer()
stock_instrument_service = stock_data_management_container.get_stock_instrument_service()


stock_instrument_service.update_instruments_profile(batch_size=100)