from enum import Enum


class FinancialMetric(str, Enum):
    PROFIT_BEFORE_TAX = "PROFIT_BEFORE_TAX"
    INCOME_BEFORE_WC_CHANGES = "INCOME_BEFORE_WC_CHANGES" 
    CHANGE_IN_ASSETS = "CHANGE_IN_ASSETS" 
    CHANGE_IN_LIABILITIES = "CHANGE_IN_LIABILITIES"
    CHANGE_IN_WC = "CHANGE_IN_WC"
    CASH_FLOW_FROM_OPERATIONS = "CASH_FLOW_FROM_OPERATIONS"
    CASH_FLOW_FROM_INVESTING = "CASH_FLOW_FROM_INVESTING" 
    CASH_FLOW_FROM_FINANCING = "CASH_FLOW_FROM_FINANCING" 
    TOTAL_CASH_FLOW = "TOTAL_CASH_FLOW"
    CASH_START_OF_YEAR = "CASH_START_OF_YEAR"
    CASH_END_OF_YEAR = "CASH_END_OF_YEAR"

    OPERATING = "OPERATING"
    INVESTING = "INVESTING" 
    FINANCING = "FINANCING"

    NON_CURRENT_ASSETS = "NON_CURRENT_ASSETS"
    CURRENT_ASSETS = "CURRENT_ASSETS"
    TOTAL_ASSETS = "TOTAL_ASSETS"
    CURRENT_LIABILITIES = "CURRENT_LIABILITIES" 
    NET_CURRENT_ASSET = "NET_CURRENT_ASSET" 
    NON_CURRENT_LIABILITIES = "NON_CURRENT_LIABILITIES"
    EQUITY_CAPITAL = "EQUITY_CAPITAL" 
    TOTAL_EQUITY_LIABILITIES = "TOTAL_EQUITY_LIABILITIES" 

    REVENUE = "REVENUE"
    OPERATING_PROFIT = "OPERATING_PROFIT"
    NET_PROFIT = "NET_PROFIT"

    REVENUE_REPORTED = "REVENUE_REPORTED"
    OTHER_INCOME = "OTHER_INCOME"
    TOTAL_REVENUE = "TOTAL_REVENUE"
    TOTAL_EXPENSES = "TOTAL_EXPENSES"
    PROFIT_BEFORE_TAX_REPORTED = "PROFIT_BEFORE_TAX_REPORTED"
    TAX = "TAX"
    PROFIT_AFTER_TAX = "PROFIT_AFTER_TAX"
    EPS_BASIC = "EPS_BASIC"
    EPS_DILUTED = "EPS_DILUTED"